Migrate Repository to Charmed Kubernetes Org
charmed-kubernetes/k8s-dashboard-operator pull request #1
Opened 2020-10-30 14:13 UTC by DomFleischmann

This PR englobes all the current work done on my personal Repository.

2020-10-30 16:27 UTC, johnsca requested changes
Mostly looks good, but a few things below.

2020-10-30 16:27 UTC, johnsca commented on README.md
> +=======
I think you want to drop lines 1 & 2 here.

2020-10-30 16:27 UTC, johnsca commented on README.md
> +2. build both charms:
Double twos.

2020-10-30 16:27 UTC, johnsca commented on README.md
> +<localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:8443/proxy/>
```suggestion
<http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:8443/proxy/>
```

2020-10-30 16:27 UTC, johnsca commented on README.md
> +In case you are deploying to a different namespaces than `kubernetes-dashboard`, you will  have to write that namespace after `v1/namespaces/`.
```suggestion
If you deploy to a different namespace than `kubernetes-dashboard`, you will have to replace the `kubernetes-dashboard` portion of the URL with the correct namespace.
```

2020-10-30 16:27 UTC, johnsca commented on charms/dashboard-metrics-scraper/README.md
> +A Kubernetes Operator for the Kubernetes Dashboard
Once this is done, we'll need to create a proper docs page for these charms and link to them from here.  Just a note to remember to do that when appropriate.

2020-10-30 16:27 UTC, johnsca commented on charms/dashboard-metrics-scraper/src/charm.py
> +        self.service_data = ProvideK8sService(self, 'metrics-scraper')
I don't see where this is actually used.  It could presumably know when to and do the data sending on it's own, and could determine the service name from the model, but it seems like it would at least need to know what port to send, since that's configurable, right?

2020-10-30 16:27 UTC, johnsca commented on charms/kubernetes-dashboard/src/charm.py
> +                return
I'm not sure that I like this pattern of having a config controlling whether a relation is optional or not. Typically, we would just check if the relation exists (either by the existence of a relation ID, having seen the `relation-created` hook, or using `goal-state` [[caveat](https://github.com/canonical/operator/issues/434)]) and then either use the default `--metrics-provider=none` if no relation or set a `WaitingStatus` if the relation data isn't available yet.

As-is, you could get into a state where the relation is added but ignored because of the config, and you'll also report `blocked` when you're actually just `waiting` on relation data to come in. I also don't know that you gain anything by including the config since the presence of the relation or not really already indicates the user's intention (LMK if I'm missing something there, though).  If the concern is about doing extra work starting things up with no metrics and then having to reconfigure, I think that only used to be an issue when all we had was `relation-joined`; both the relation ID and `relation-created` event should be visible early enough for it to not matter, but even if not, with K8s it's also much less of an issue to re-spin the pod when the model changes (which might happen anyway if the relation was added manually after the fact, rather than using a bundle).

2020-10-30 16:27 UTC, johnsca commented on charms/kubernetes-dashboard/src/charm.py
> +                return
Oh, it might also be worth noting that it looks like there may be an `optional` flag for relations coming at some point, at least according to [this Discourse post](https://discourse.juju.is/t/charm-metadata-v2/3674).

2020-10-30 16:27 UTC, johnsca commented on charms/dashboard-metrics-scraper/src/charm.py
> +        self.service_data = ProvideK8sService(self, 'metrics-scraper')
There's also a bit of a mismatch between the library / class name ("K8s service") and the interface protocol name ("metrics scraper"), and it might be better if those were more aligned.  The relation endpoint name could still be `metrics-scraper` for a given charm, though.

2020-10-30 16:27 UTC, johnsca commented on charms/dashboard-metrics-scraper/requirements.txt
> +git+https://github.com/DomFleischmann/interface-k8s-service.git
It looks like you might be using pipenv, but you're not generating your `requirements.txt` with it and this req is missing from your `Pipfile`.  I'm still on the fence if it's worth using the pipenv approach yet with operator framework / k8s charms, so open to discussion as to whether it makes more sense to drop those or fix this.

2020-10-30 16:27 UTC, johnsca commented on charms/kubernetes-dashboard/config.yaml
> +      the same order as provided. Multiple options can be used at once. Supported
Worth specifying what format should be used for multiple values (presumably CSV?).

2020-10-30 16:27 UTC, johnsca commented on charms/kubernetes-dashboard/config.yaml
> +      has '--authorization-mode=ABAC' and '--basic-auth-file' flags set.
Wow, this is actually the first time I've heard of ABAC for K8s and honestly thought that was a typo at first. 😅 But given that basic auth has been removed entirely as of 1.19, is it worth supporting this?  I suppose this could still be used with older K8s but it seems a shame to have to carry this forward.

2020-10-30 16:27 UTC, johnsca commented on docs/local-overlay.yaml
> +  2) build both charms:
2-2 again.

2020-11-03 09:23 UTC, DomFleischmann commented on README.md
> +In case you are deploying to a different namespaces than `kubernetes-dashboard`, you will  have to write that namespace after `v1/namespaces/`.
Glad you pointed that out, with the second service which maps to the 443 port you won't have to state the namespace. So I'll remove that part.

2020-11-03 12:56 UTC, DomFleischmann commented on charms/kubernetes-dashboard/config.yaml
> +      has '--authorization-mode=ABAC' and '--basic-auth-file' flags set.
I've copied this description from the dashboard docs. Considering that there are only 2 options and we might not want to support `basic` maybe this config option is not needed.

2020-11-03 14:38 UTC, DomFleischmann commented on charms/dashboard-metrics-scraper/requirements.txt
> +git+https://github.com/DomFleischmann/interface-k8s-service.git
I'm in favor of using tools like pipenv in charms, so I will update the requirements.txt. 

Regarding pipenv vs pip-tools I don't really have an opinion because I haven't used all of them.

2020-11-03 21:01 UTC, johnsca approved these changes
I think this is good to land, with the understanding that we will have discussions with the Charm Craft team to ensure that we are using the best patterns and to iterate on this further (primarily around the interface API component design).

2020-11-03 21:01 UTC, merged